-- ======================================================================
-- MISSION CONTROL : INSFORGE SCHEMA DEFINITIONS
-- Run this in your InsForge interface (Supabase SQL Editor)
-- Purpose: Persistent real-time tracking of ACHEEVY OODA pipeline loops.
-- ======================================================================

-- 1. Tasks & Objectives (TEPs)
CREATE TABLE public.acheevy_tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    objective TEXT NOT NULL,
    requested_by TEXT DEFAULT 'A.I.M.S_Owner',
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'drafted', -- drafted, active, complete, failed
    chain TEXT,
    assigned_role TEXT,
    grade VARCHAR(2)
);

-- 2. Pipeline Execution State (Real-Time DAG Node Tracker)
CREATE TABLE public.acheevy_pipeline_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    task_id UUID REFERENCES public.acheevy_tasks(id) ON DELETE CASCADE,
    active_node TEXT DEFAULT 'idle',
    started_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    status TEXT DEFAULT 'running', -- running, complete, failed, escalated
    node_states JSONB DEFAULT '{}'::jsonb -- Stores complete/standby state per agent node
);

-- 3. Node Event Logs (SYS.STREAM Data)
CREATE TABLE public.acheevy_node_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id UUID REFERENCES public.acheevy_pipeline_runs(id) ON DELETE CASCADE,
    node_id TEXT NOT NULL,
    log_message TEXT NOT NULL,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. InsForge Realtime Setup
-- Enable real-time broadcasting so Mission Control doesn't need to poll via HTTP.
ALTER PUBLICATION supabase_realtime ADD TABLE acheevy_tasks;
ALTER PUBLICATION supabase_realtime ADD TABLE acheevy_pipeline_runs;
ALTER PUBLICATION supabase_realtime ADD TABLE acheevy_node_logs;

-- Security Policies (Basic RLS for isolated environments)
ALTER TABLE public.acheevy_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.acheevy_pipeline_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.acheevy_node_logs ENABLE ROW LEVEL SECURITY;

-- Temporarily allow all for API usage (Update policies when moving to strict production)
CREATE POLICY "Allow Service Role API" ON public.acheevy_tasks FOR ALL USING (true);
CREATE POLICY "Allow Service Role API" ON public.acheevy_pipeline_runs FOR ALL USING (true);
CREATE POLICY "Allow Service Role API" ON public.acheevy_node_logs FOR ALL USING (true);
