// Path assumes this file lives at src/Backend/Validation/
// and luc.constants.ts is at the repo root under aims-tools/luc/
const KYB_ROUTING_DECISIONS = {
  APPROVED_STANDARD: 'Approved_Standard',
  OPS_MANUAL_REVIEW: 'Ops_Ang_Manual_Review',
  AUTO_REJECTED: 'Auto_Rejected',
  PENDING_EVIDENCE: 'Pending_Evidence'
} as const;

const KYB_RISK_THRESHOLDS = {
  LOW: 0.3,
  MEDIUM: 0.6,
  HIGH: 0.85
} as const;

// ─── KYB Onboarding Payload Contract ────────────────────────────
// This is the exact shape that Stepper must send to the /kyb-onboard webhook.
// SME_Stepper_Ang + SME_Paperform_Ang jointly own this contract.

export interface KYBOnboardPayload {
  /** Paperform submission ID (auto-generated by Paperform) */
  submissionId: string;

  /** Email of the human operator registering the Boomer_Ang */
  ownerEmail: string;

  /** Display name for the new agent */
  boomerAngName: string;

  /** Primary skill classification (e.g., "Code Refactoring", "Research", "Design") */
  primarySkill: string;

  /** List of capabilities the agent is authorized for */
  capabilities: string[];

  /** Hard limitations (e.g., "Cannot access production databases") */
  limitations: string[];

  /** Privacy preferences */
  privacy: {
    dataRetention: '7d' | '30d' | '90d' | 'indefinite';
    humanReviewPolicy: 'always' | 'on_error' | 'never';
    modelTrainingOptOut: boolean;
  };

  /** Outcome score calculated by Paperform (0.0 to 1.0) */
  outcomeScore: number;

  /** Optional: category label from Paperform calculator */
  outcomeLabel?: string;

  /** Timestamp of when the form was submitted (ISO 8601) */
  submittedAt: string;
}

// ─── Flight Recorder Entry ──────────────────────────────────────
// The LUC writes this record for every KYB onboarding event.

export interface KYBFlightRecorderEntry {
  timestamp: string;
  eventId: string;
  angSerialId: string;

  executionLog: {
    phase: 'REGISTRATION';
    inputHash: string;       // SHA-256 of the raw payload
    outcomeScore: number;
    outcomeLabel?: string;
  };

  routingDecision: keyof typeof KYB_ROUTING_DECISIONS;

  verificationResults: {
    payloadValid: boolean;
    requiredFieldsPresent: boolean;
    riskTierAssigned: 'LOW' | 'MEDIUM' | 'HIGH';
  };

  costMetrics: {
    tokensUsed: number;
    executionTimeMs: number;
  };
}

// ─── Anchor Chain Event ─────────────────────────────────────────
// Generated after Flight Recorder entry is confirmed.

export interface KYBAnchorEvent {
  batchId: string;
  merkleRoot: string;
  eventCount: number;
  blockchainTx?: string;      // Populated after anchoring

  validations: {
    proofOfAction: boolean;   // The registration actually happened
    proofOfQuality: boolean;  // The registration passed verification
  };
}

// ─── Validation Helpers ─────────────────────────────────────────

export function validateKYBPayload(body: unknown): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  const payload = body as Partial<KYBOnboardPayload>;

  if (!payload.submissionId) errors.push('Missing submissionId');
  if (!payload.ownerEmail) errors.push('Missing ownerEmail');
  if (!payload.boomerAngName) errors.push('Missing boomerAngName');
  if (!payload.primarySkill) errors.push('Missing primarySkill');
  if (!payload.capabilities || !Array.isArray(payload.capabilities)) errors.push('capabilities must be an array');
  if (!payload.limitations || !Array.isArray(payload.limitations)) errors.push('limitations must be an array');
  if (typeof payload.outcomeScore !== 'number' || payload.outcomeScore < 0 || payload.outcomeScore > 1) {
    errors.push('outcomeScore must be a number between 0.0 and 1.0');
  }
  if (!payload.submittedAt) errors.push('Missing submittedAt timestamp');

  // Privacy block validation
  if (!payload.privacy) {
    errors.push('Missing privacy block');
  } else {
    const validRetentions = ['7d', '30d', '90d', 'indefinite'];
    if (!validRetentions.includes(payload.privacy.dataRetention)) errors.push('Invalid dataRetention value');
    const validReview = ['always', 'on_error', 'never'];
    if (!validReview.includes(payload.privacy.humanReviewPolicy)) errors.push('Invalid humanReviewPolicy');
    if (typeof payload.privacy.modelTrainingOptOut !== 'boolean') errors.push('modelTrainingOptOut must be boolean');
  }

  return { valid: errors.length === 0, errors };
}

export function classifyRiskTier(outcomeScore: number): 'LOW' | 'MEDIUM' | 'HIGH' {
  if (outcomeScore <= KYB_RISK_THRESHOLDS.LOW) return 'LOW';
  if (outcomeScore <= KYB_RISK_THRESHOLDS.MEDIUM) return 'MEDIUM';
  return 'HIGH';
}

export function determineRoutingDecision(riskTier: 'LOW' | 'MEDIUM' | 'HIGH'): string {
  switch (riskTier) {
    case 'LOW': return KYB_ROUTING_DECISIONS.APPROVED_STANDARD;
    case 'MEDIUM': return KYB_ROUTING_DECISIONS.APPROVED_STANDARD;
    case 'HIGH': return KYB_ROUTING_DECISIONS.OPS_MANUAL_REVIEW;
    default: return KYB_ROUTING_DECISIONS.PENDING_EVIDENCE;
  }
}
