import { GrammarState } from '../state';
import { VlJepaService } from '../services/vl_jepa';

/**
 * Review/Hone Role: Validates, corrects, and gates release.
 * Ensures the specialist's draft meets all constraints and passes policy checks.
 * Integrates hallucination detection (e.g. via VL-JEPA metrics or LLM judge).
 */
export async function runReviewHone(state: GrammarState): Promise<Partial<GrammarState>> {
  console.log('[Review_Hone] Reviewing generated draft...');

  const errors: string[] = [];

  // 1. Check if draft exists
  if (!state.currentDraft) {
    errors.push('No draft was generated by specialist.');
  }

  // 2. Validate against explicit constraints
  if (state.constraints) {
    for (const constraint of state.constraints) {
      if (!state.currentDraft?.includes(constraint.split(' ')[0])) {
        // Mock constraint check - simplified for now
        // A real check would use an LLM or AST tool 
        console.log(`[Review_Hone] Note: Draft might not directly fulfill constraint: ${constraint}`);
      }
    }
  }

  // 3. VL-JEPA Hallucination check
  const analysis = await VlJepaService.analyzeDraft(
    state.normalizedObjective || state.rawIntent, 
    state.currentDraft ?? '', 
    state.contextPack
  );
  
  const hallucinationScore = analysis.hallucinationScore;
  
  if (hallucinationScore > 8) {
    errors.push(`High hallucination risk detected via VL-JEPA (Score: ${hallucinationScore.toFixed(2)})`);
  }
  
  if (analysis.flags.length > 0) {
    // Add flags as warnings or distinct errors
    errors.push(...analysis.flags);
  }

  if (errors.length > 0) {
    console.warn(`[Review_Hone] Draft failed review. Errors:`, errors);
    return {
      validationErrors: errors,
      approvedForAssembly: false,
      boardState: 'blocked',
      hallucinationScore
    };
  }

  console.log('[Review_Hone] Draft approved for assembly.');
  return {
    validationErrors: [],
    approvedForAssembly: true,
    boardState: 'approved',
    hallucinationScore
  };
}
